name: zed # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: "0.149.5" # just for humans, typically '1.2+git' or '1.3.2'
compression: lzo
summary: A high-performance, multiplayer code editor # 79 char long summary
description: |
  Code at the speed of thought – Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
apps:
  zed:
    command: usr/bin/zed
parts:
  zed:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/zed-industries/zed
    source-tag: "v0.149.5"
    source-type: git
    build-snaps:
      - rustup
    build-packages:
      - gcc
      - g++
      - libasound2-dev
      - libfontconfig-dev
      - libwayland-dev
      - libxkbcommon-x11-dev
      - libssl-dev
      - libstdc++-12-dev
      - libzstd-dev
      - libvulkan1
      - libgit2-dev
      - make
      - clang
      - mold
      - jq
      - gettext-base
      - elfutils
      - libsqlite3-dev
    override-build: |
      craftctl default
      rustup update
      cargo build --release --package cli --package zed
      mkdir -p ${CRAFT_PART_INSTALL}/usr/bin
      mkdir -p ${CRAFT_PART_INSTALL}/usr/libexec
      cp target/release/cli ${CRAFT_PART_INSTALL}/usr/bin/zed
      cp target/release/zed ${CRAFT_PART_INSTALL}/usr/libexec/zed-editor
